CLASS LHC_ZZCIR_CIT_TAP_22CZ051 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitTap22cz051
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_TAP_22CZ051 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
